# Configurações específicas para o perfil de Desenvolvimento
server.port=8080

# TODO: Configurar conexão com banco de dados
# spring.datasource.url=jdbc:postgresql://localhost:5432/a3_2_0
# spring.datasource.username=postgres
# spring.datasource.password=
# spring.datasource.driver-class-name=org.postgresql.Driver

# TODO: Configurar JPA/Hibernate
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true