# =====================================================
# CONEXÃO COM SQLITE (BANCO LOCAL)
# =====================================================
spring.datasource.url=jdbc:sqlite:a3_2_0.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# =====================================================
# JPA / HIBERNATE
# =====================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# =====================================================
# OUTROS
# =====================================================
spring.sql.init.mode=never
spring.h2.console.enabled=false